# Site settings
title: elDevShow
email: hola@eldevshow.com
description: > # this means to ignore newlines until "baseurl:"
  Amamos programar, amamos aprender y nos apasiona enseñar y compartir,
  por eso entrevistamos a gente bien chingona en la comunidad de devs
  para inspirarnos y aprender de ellos, Si tú también te estas
  construyendo una carrera como dev; este podcast es para ti.
baseurl: "" # the subpath of your site, e.g. /blog/
# url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: elDevShow
github_username:  jekyll

# Build settings
markdown: kramdown


paginate: 4
paginate_path: "blog/page:num"